export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const GET_MOST_RECENT_UPLOAD_SUCCESS = 'GET_MOST_RECENT_UPLOAD_SUCCESS';
export const GET_RECENT_UPLOADS_PLAYLIST_SUCCESS = 'GET_RECENT_UPLOADS_PLAYLIST_SUCCESS';