export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const GET_MOST_RECENT_UPLOAD_SUCCESS = 'GET_MOST_RECENT_UPLOAD_SUCCESS';
export const GET_RECENT_UPLOADS_PLAYLIST_SUCCESS = 'GET_RECENT_UPLOADS_PLAYLIST_SUCCESS';

export const GET_ALL_PLAYLISTS_SUCCESS = 'GET_ALL_PLAYLISTS_SUCCESS';
export const GET_NEXT_PLAYLISTS_SUCCESS = 'GET_NEXT_PLAYLISTS_SUCCESS';
export const GET_PLAYLIST_SUCCESS = 'GET_PLAYLIST_SUCCESS';
export const GET_NEXT_VIDEOS_SUCCESS = 'GET_NEXT_VIDEOS_SUCCESS';
export const GET_PLAYLIST_INFO_SUCCESS = 'GET_PLAYLIST_INFO_SUCCESS';

export const GET_VIDEO_SUCCESS = 'GET_VIDEO_SUCCESS';