/* CLEAR STORE TYPE */
export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';
export const CLEAR_COMMENTS = 'CLEAR_COMMENTS';
export const CLEAR_LIKES = 'CLEAR_LIKES';
export const CLEAR_DISLIKES = 'CLEAR_DISLIKES';
export const CLEAR_REVENUE = 'CLEAR_REVENUE';
export const CLEAR_AD_REVENUE = 'CLEAR_AD_REVENUE';
export const CLEAR_YOUTUBE_RED_REVENUE = 'CLEAR_YOUTUBE_RED_REVENUE';
export const CLEAR_SUBSCRIBERS = 'CLEAR_SUBSCRIBERS';
export const CLEAR_UNSUBSCRIBERS = 'CLEAR_UNSUBSCRIBERS';
export const CLEAR_VIEWS = 'CLEAR_VIEWS';
export const CLEAR_WATCH_TIME = 'CLEAR_WATCH_TIME';

/* AJAX CALL TYPES */
export const LOGGING_IN = 'LOGGING_IN';
export const GETTING_IS_LOGGED_IN = 'GETTING_IS_LOGGED_IN';

export const GETTING_CHANNEL_INFO = 'GETTING_CHANNEL_INFO';
export const SEARCHING_CHANNEL = 'SEARCHING_CHANNEL';
export const GETTING_COMMENTS = 'GETTING_COMMENTS';
export const GETTING_LIKES = 'GETTING_LIKES';
export const GETTING_DISLIKES = 'GETTING_DISLIKES';
export const GETTING_REVENUE = 'GETTING_REVENUE';
export const GETTING_AD_REVENUE = 'GETTING_AD_REVENUE';
export const GETTING_YOUTUBE_RED_REVENUE = 'GETTING_YOUTUBE_RED_REVENUE';
export const GETTING_SUBSCRIBERS = 'GETTING_SUBSCRIBERS';
export const GETTING_UNSUBSCRIBERS = 'GETTING_UNSUBSCRIBERS';
export const GETTING_VIEWS = 'GETTING_VIEWS';
export const GETTING_WATCH_TIME = 'GETTING_WATCH_TIME';
export const GETTING_TOTAL_STATS = 'GETTING_TOTAL_STATS';

/* ACTION SUCCESS TYPES */
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const GET_IS_LOGGED_IN_SUCCESS = 'GET_IS_LOGGED_IN_SUCCESS';

export const GET_CHANNEL_INFO_SUCCESS = 'GET_CHANNEL_INFO_SUCCESS';
export const GET_SEARCH_CHANNEL_RESULTS_SUCCESS = 'GET_SEARCH_CHANNEL_RESULTS_SUCCESS';
export const GET_SEARCH_PLAYLIST_RESULTS_SUCCESS = 'GET_SEARCH_PLAYLIST_RESULTS_SUCCESS';
export const GET_SEARCH_VIDEO_RESULTS_SUCCESS = 'GET_SEARCH_VIDEO_RESULTS_SUCCESS';
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const GET_LIKES_SUCCESS = 'GET_LIKES_SUCCESS';
export const GET_DISLIKES_SUCCESS = 'GET_DISLIKES_SUCCESS';
export const GET_REVENUE_SUCCESS = 'GET_REVENUE_SUCCESS';
export const GET_AD_REVENUE_SUCCESS = 'GET_AD_REVENUE_SUCCESS';
export const GET_YOUTUBE_RED_REVENUE_SUCCESS = 'GET_YOUTUBE_RED_REVENUE_SUCCESS';
export const GET_SUBSCRIBERS_SUCCESS = 'GET_SUBSCRIBERS_SUCCESS';
export const GET_UNSUBSCRIBERS_SUCCESS = 'GET_UNSUBSCRIBERS_SUCCESS';
export const GET_VIEWS_SUCCESS = 'GET_VIEWS_SUCCESS';
export const GET_WATCH_TIME_SUCCESS = 'GET_WATCH_TIME_SUCCESS';
export const GET_TOTAL_STATS_SUCCESS = 'GET_TOTAL_STATS_SUCCESS';

/* ACTION ERROR TYPES */
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const GET_IS_LOGGED_IN_ERROR = 'GET_IS_LOGGED_IN_ERROR';

export const GET_CHANNEL_INFO_ERROR = 'GET_CHANNEL_INFO_ERROR';
export const GET_COMMENTS_ERROR = 'GET_COMMENTS_ERROR';
export const GET_LIKES_ERROR = 'GET_LIKES_ERROR';
export const GET_DISLIKES_ERROR = 'GET_DISLIKES_ERROR';
export const GET_REVENUE_ERROR = 'GET_REVENUE_ERROR';
export const GET_AD_REVENUE_ERROR = 'GET_AD_REVENUE_ERROR';
export const GET_YOUTUBE_RED_REVENUE_ERROR = 'GET_YOUTUBE_RED_REVENUE_ERROR';
export const GET_SUBSCRIBERS_ERROR = 'GET_SUBSCRIBERS_ERROR';
export const GET_UNSUBSCRIBERS_ERROR = 'GET_UNSUBSCRIBERS_ERROR';
export const GET_VIEWS_ERROR = 'GET_VIEWS_ERROR';
export const GET_WATCH_ERROR = 'GET_WATCH_ERROR';
export const GET_TOTAL_STATS_ERROR = 'GET_TOTAL_STATS_ERROR';
export const GET_SEARCH_RESULTS_ERROR = 'GET_SEARCH_RESULTS_ERROR';