/* FILTER / GRAPH STATE */
export const SET_FILTER_STATE = 'SET_FILTER_STATE';
export const SET_GRAPH_TYPE = 'SET_GRAPH_TYPE';

/* CLEAR STORE TYPE */
export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';
export const CLEAR_REPORT = 'CLEAR_REPORT';

/* AJAX CALL TYPES */
export const LOGGING_IN = 'LOGGING_IN';
export const GETTING_IS_LOGGED_IN = 'GETTING_IS_LOGGED_IN';

export const GETTING_CHANNEL_INFO = 'GETTING_CHANNEL_INFO';
export const SEARCHING_CHANNEL = 'SEARCHING_CHANNEL';

export const GETTING_REPORT = 'GETTING_REPORT';
export const GETTING_TOTAL_STATS = 'GETTING_TOTAL_STATS';

/* ACTION SUCCESS TYPES */
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const GET_IS_LOGGED_IN_SUCCESS = 'GET_IS_LOGGED_IN_SUCCESS';

export const GET_CHANNEL_INFO_SUCCESS = 'GET_CHANNEL_INFO_SUCCESS';
export const GET_SEARCH_CHANNEL_RESULTS_SUCCESS = 'GET_SEARCH_CHANNEL_RESULTS_SUCCESS';
export const GET_SEARCH_PLAYLIST_RESULTS_SUCCESS = 'GET_SEARCH_PLAYLIST_RESULTS_SUCCESS';
export const GET_SEARCH_VIDEO_RESULTS_SUCCESS = 'GET_SEARCH_VIDEO_RESULTS_SUCCESS';

export const GET_REPORT_SUCCESS = 'GET_REPORT_SUCCESS';
export const GET_TOTAL_STATS_SUCCESS = 'GET_TOTAL_STATS_SUCCESS';

/* ACTION ERROR TYPES */
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const GET_IS_LOGGED_IN_ERROR = 'GET_IS_LOGGED_IN_ERROR';

export const GET_CHANNEL_INFO_ERROR = 'GET_CHANNEL_INFO_ERROR';
export const GET_SEARCH_RESULTS_ERROR = 'GET_SEARCH_RESULTS_ERROR';

export const GET_REPORT_ERROR = 'GET_REPORT_ERROR';
export const GET_TOTAL_STATS_ERROR = 'GET_TOTAL_STATS_ERROR';