/* AJAX CALL TYPES */
export const LOGGING_IN = 'LOGGING_IN';
export const GETTING_IS_LOGGED_IN = 'GETTING_IS_LOGGED_IN';

/* ACTION SUCCESS TYPES */
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const GET_IS_LOGGED_IN_SUCCESS = 'GET_IS_LOGGED_IN_SUCCESS';