const DataTypes = {
    CURRENCY: 'CURRENCY',
    DECIMAL: 'DECIMAL',
    NUMBER: 'NUMBER',
    PERCENTAGE: 'PERCENTAGE',
    RATIO: 'RATIO',
    TIME_MINUTES: 'TIME_MINUTES',
    TIME_SECONDS: 'TIME_SECONDS'
};

export default DataTypes;