export default {
    channelInfo: {},
    comments: {},
    dislikes: {},
    likes: {},
    revenue: {},
    adRevenue: {},
    youtubeRedRevenue: {},
    searchChannelResults: [],
    searchPlaylistResults: [],
    searchVideoResults: [],
    subscribers: {},
    unsubscribers: {},
    totalStats: {},
    views: {},
    watchTime: {},
    isAuthenticated: false,
    ajaxCallsInProgress: {
        adRevenue: 0,
        channel: 0,
        comments: 0,
        contentFilter: 0,
        dislikes: 0,
        isLoggedIn: 0,
        likes: 0,
        login: 0,
        revenue: 0,
        subscribers: 0,
        totalStats: 0,
        unsubscribers: 0,
        views: 0,
        watchTime: 0,
        youtubeRedRevenue: 0
    }
};